// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: force_master_pub.proto

#include "force_master_pub.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_force_5fmaster_5fpub_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_force_5fmaster_5fpub_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_CartPose;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_force_5fmaster_5fpub_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_JointPosition;
}  // namespace protobuf_force_5fmaster_5fpub_2eproto
namespace ForceMasterPub {
class PublishDataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PublishData>
      _instance;
} _PublishData_default_instance_;
class JointPositionDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<JointPosition>
      _instance;
} _JointPosition_default_instance_;
class CartPoseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CartPose>
      _instance;
} _CartPose_default_instance_;
}  // namespace ForceMasterPub
namespace protobuf_force_5fmaster_5fpub_2eproto {
static void InitDefaultsPublishData() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ForceMasterPub::_PublishData_default_instance_;
    new (ptr) ::ForceMasterPub::PublishData();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ForceMasterPub::PublishData::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_PublishData =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsPublishData}, {
      &protobuf_force_5fmaster_5fpub_2eproto::scc_info_JointPosition.base,
      &protobuf_force_5fmaster_5fpub_2eproto::scc_info_CartPose.base,}};

static void InitDefaultsJointPosition() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ForceMasterPub::_JointPosition_default_instance_;
    new (ptr) ::ForceMasterPub::JointPosition();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ForceMasterPub::JointPosition::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_JointPosition =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsJointPosition}, {}};

static void InitDefaultsCartPose() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ForceMasterPub::_CartPose_default_instance_;
    new (ptr) ::ForceMasterPub::CartPose();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ForceMasterPub::CartPose::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CartPose =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCartPose}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_PublishData.base);
  ::google::protobuf::internal::InitSCC(&scc_info_JointPosition.base);
  ::google::protobuf::internal::InitSCC(&scc_info_CartPose.base);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ForceMasterPub::PublishData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ForceMasterPub::PublishData, joint_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ForceMasterPub::PublishData, pose_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ForceMasterPub::JointPosition, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ForceMasterPub::JointPosition, joint_num_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ForceMasterPub::JointPosition, joint_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ForceMasterPub::CartPose, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ForceMasterPub::CartPose, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ForceMasterPub::CartPose, y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ForceMasterPub::CartPose, z_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ForceMasterPub::CartPose, a_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ForceMasterPub::CartPose, b_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ForceMasterPub::CartPose, c_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ForceMasterPub::PublishData)},
  { 7, -1, sizeof(::ForceMasterPub::JointPosition)},
  { 14, -1, sizeof(::ForceMasterPub::CartPose)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::ForceMasterPub::_PublishData_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::ForceMasterPub::_JointPosition_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::ForceMasterPub::_CartPose_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "force_master_pub.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\026force_master_pub.proto\022\016ForceMasterPub"
      "\"c\n\013PublishData\022,\n\005joint\030\001 \001(\0132\035.ForceMa"
      "sterPub.JointPosition\022&\n\004pose\030\002 \001(\0132\030.Fo"
      "rceMasterPub.CartPose\"1\n\rJointPosition\022\021"
      "\n\tjoint_num\030\001 \001(\005\022\r\n\005joint\030\002 \003(\001\"L\n\010Cart"
      "Pose\022\t\n\001x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\022\t\n\001z\030\003 \001(\001\022\t\n"
      "\001a\030\004 \001(\001\022\t\n\001b\030\005 \001(\001\022\t\n\001c\030\006 \001(\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 278);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "force_master_pub.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_force_5fmaster_5fpub_2eproto
namespace ForceMasterPub {

// ===================================================================

void PublishData::InitAsDefaultInstance() {
  ::ForceMasterPub::_PublishData_default_instance_._instance.get_mutable()->joint_ = const_cast< ::ForceMasterPub::JointPosition*>(
      ::ForceMasterPub::JointPosition::internal_default_instance());
  ::ForceMasterPub::_PublishData_default_instance_._instance.get_mutable()->pose_ = const_cast< ::ForceMasterPub::CartPose*>(
      ::ForceMasterPub::CartPose::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PublishData::kJointFieldNumber;
const int PublishData::kPoseFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PublishData::PublishData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_force_5fmaster_5fpub_2eproto::scc_info_PublishData.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ForceMasterPub.PublishData)
}
PublishData::PublishData(const PublishData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_joint()) {
    joint_ = new ::ForceMasterPub::JointPosition(*from.joint_);
  } else {
    joint_ = NULL;
  }
  if (from.has_pose()) {
    pose_ = new ::ForceMasterPub::CartPose(*from.pose_);
  } else {
    pose_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:ForceMasterPub.PublishData)
}

void PublishData::SharedCtor() {
  ::memset(&joint_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&pose_) -
      reinterpret_cast<char*>(&joint_)) + sizeof(pose_));
}

PublishData::~PublishData() {
  // @@protoc_insertion_point(destructor:ForceMasterPub.PublishData)
  SharedDtor();
}

void PublishData::SharedDtor() {
  if (this != internal_default_instance()) delete joint_;
  if (this != internal_default_instance()) delete pose_;
}

void PublishData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PublishData::descriptor() {
  ::protobuf_force_5fmaster_5fpub_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_force_5fmaster_5fpub_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PublishData& PublishData::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_force_5fmaster_5fpub_2eproto::scc_info_PublishData.base);
  return *internal_default_instance();
}


void PublishData::Clear() {
// @@protoc_insertion_point(message_clear_start:ForceMasterPub.PublishData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && joint_ != NULL) {
    delete joint_;
  }
  joint_ = NULL;
  if (GetArenaNoVirtual() == NULL && pose_ != NULL) {
    delete pose_;
  }
  pose_ = NULL;
  _internal_metadata_.Clear();
}

bool PublishData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ForceMasterPub.PublishData)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .ForceMasterPub.JointPosition joint = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_joint()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .ForceMasterPub.CartPose pose = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_pose()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ForceMasterPub.PublishData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ForceMasterPub.PublishData)
  return false;
#undef DO_
}

void PublishData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ForceMasterPub.PublishData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .ForceMasterPub.JointPosition joint = 1;
  if (this->has_joint()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_joint(), output);
  }

  // .ForceMasterPub.CartPose pose = 2;
  if (this->has_pose()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_pose(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ForceMasterPub.PublishData)
}

::google::protobuf::uint8* PublishData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ForceMasterPub.PublishData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .ForceMasterPub.JointPosition joint = 1;
  if (this->has_joint()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_joint(), deterministic, target);
  }

  // .ForceMasterPub.CartPose pose = 2;
  if (this->has_pose()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_pose(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ForceMasterPub.PublishData)
  return target;
}

size_t PublishData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ForceMasterPub.PublishData)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .ForceMasterPub.JointPosition joint = 1;
  if (this->has_joint()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *joint_);
  }

  // .ForceMasterPub.CartPose pose = 2;
  if (this->has_pose()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *pose_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PublishData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ForceMasterPub.PublishData)
  GOOGLE_DCHECK_NE(&from, this);
  const PublishData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PublishData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ForceMasterPub.PublishData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ForceMasterPub.PublishData)
    MergeFrom(*source);
  }
}

void PublishData::MergeFrom(const PublishData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ForceMasterPub.PublishData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_joint()) {
    mutable_joint()->::ForceMasterPub::JointPosition::MergeFrom(from.joint());
  }
  if (from.has_pose()) {
    mutable_pose()->::ForceMasterPub::CartPose::MergeFrom(from.pose());
  }
}

void PublishData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ForceMasterPub.PublishData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PublishData::CopyFrom(const PublishData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ForceMasterPub.PublishData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PublishData::IsInitialized() const {
  return true;
}

void PublishData::Swap(PublishData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PublishData::InternalSwap(PublishData* other) {
  using std::swap;
  swap(joint_, other->joint_);
  swap(pose_, other->pose_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PublishData::GetMetadata() const {
  protobuf_force_5fmaster_5fpub_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_force_5fmaster_5fpub_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void JointPosition::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int JointPosition::kJointNumFieldNumber;
const int JointPosition::kJointFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

JointPosition::JointPosition()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_force_5fmaster_5fpub_2eproto::scc_info_JointPosition.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ForceMasterPub.JointPosition)
}
JointPosition::JointPosition(const JointPosition& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      joint_(from.joint_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  joint_num_ = from.joint_num_;
  // @@protoc_insertion_point(copy_constructor:ForceMasterPub.JointPosition)
}

void JointPosition::SharedCtor() {
  joint_num_ = 0;
}

JointPosition::~JointPosition() {
  // @@protoc_insertion_point(destructor:ForceMasterPub.JointPosition)
  SharedDtor();
}

void JointPosition::SharedDtor() {
}

void JointPosition::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* JointPosition::descriptor() {
  ::protobuf_force_5fmaster_5fpub_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_force_5fmaster_5fpub_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const JointPosition& JointPosition::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_force_5fmaster_5fpub_2eproto::scc_info_JointPosition.base);
  return *internal_default_instance();
}


void JointPosition::Clear() {
// @@protoc_insertion_point(message_clear_start:ForceMasterPub.JointPosition)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  joint_.Clear();
  joint_num_ = 0;
  _internal_metadata_.Clear();
}

bool JointPosition::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ForceMasterPub.JointPosition)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 joint_num = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &joint_num_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated double joint = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_joint())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 18u, input, this->mutable_joint())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ForceMasterPub.JointPosition)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ForceMasterPub.JointPosition)
  return false;
#undef DO_
}

void JointPosition::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ForceMasterPub.JointPosition)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 joint_num = 1;
  if (this->joint_num() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->joint_num(), output);
  }

  // repeated double joint = 2;
  if (this->joint_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(2, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _joint_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteDoubleArray(
      this->joint().data(), this->joint_size(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ForceMasterPub.JointPosition)
}

::google::protobuf::uint8* JointPosition::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ForceMasterPub.JointPosition)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 joint_num = 1;
  if (this->joint_num() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->joint_num(), target);
  }

  // repeated double joint = 2;
  if (this->joint_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      2,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _joint_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleNoTagToArray(this->joint_, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ForceMasterPub.JointPosition)
  return target;
}

size_t JointPosition::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ForceMasterPub.JointPosition)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated double joint = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->joint_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _joint_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // int32 joint_num = 1;
  if (this->joint_num() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->joint_num());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void JointPosition::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ForceMasterPub.JointPosition)
  GOOGLE_DCHECK_NE(&from, this);
  const JointPosition* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const JointPosition>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ForceMasterPub.JointPosition)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ForceMasterPub.JointPosition)
    MergeFrom(*source);
  }
}

void JointPosition::MergeFrom(const JointPosition& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ForceMasterPub.JointPosition)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  joint_.MergeFrom(from.joint_);
  if (from.joint_num() != 0) {
    set_joint_num(from.joint_num());
  }
}

void JointPosition::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ForceMasterPub.JointPosition)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void JointPosition::CopyFrom(const JointPosition& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ForceMasterPub.JointPosition)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JointPosition::IsInitialized() const {
  return true;
}

void JointPosition::Swap(JointPosition* other) {
  if (other == this) return;
  InternalSwap(other);
}
void JointPosition::InternalSwap(JointPosition* other) {
  using std::swap;
  joint_.InternalSwap(&other->joint_);
  swap(joint_num_, other->joint_num_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata JointPosition::GetMetadata() const {
  protobuf_force_5fmaster_5fpub_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_force_5fmaster_5fpub_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void CartPose::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CartPose::kXFieldNumber;
const int CartPose::kYFieldNumber;
const int CartPose::kZFieldNumber;
const int CartPose::kAFieldNumber;
const int CartPose::kBFieldNumber;
const int CartPose::kCFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CartPose::CartPose()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_force_5fmaster_5fpub_2eproto::scc_info_CartPose.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ForceMasterPub.CartPose)
}
CartPose::CartPose(const CartPose& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&c_) -
    reinterpret_cast<char*>(&x_)) + sizeof(c_));
  // @@protoc_insertion_point(copy_constructor:ForceMasterPub.CartPose)
}

void CartPose::SharedCtor() {
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&c_) -
      reinterpret_cast<char*>(&x_)) + sizeof(c_));
}

CartPose::~CartPose() {
  // @@protoc_insertion_point(destructor:ForceMasterPub.CartPose)
  SharedDtor();
}

void CartPose::SharedDtor() {
}

void CartPose::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CartPose::descriptor() {
  ::protobuf_force_5fmaster_5fpub_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_force_5fmaster_5fpub_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CartPose& CartPose::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_force_5fmaster_5fpub_2eproto::scc_info_CartPose.base);
  return *internal_default_instance();
}


void CartPose::Clear() {
// @@protoc_insertion_point(message_clear_start:ForceMasterPub.CartPose)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&c_) -
      reinterpret_cast<char*>(&x_)) + sizeof(c_));
  _internal_metadata_.Clear();
}

bool CartPose::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ForceMasterPub.CartPose)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // double x = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double y = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double z = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &z_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double a = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(33u /* 33 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &a_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double b = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(41u /* 41 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &b_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double c = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(49u /* 49 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &c_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ForceMasterPub.CartPose)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ForceMasterPub.CartPose)
  return false;
#undef DO_
}

void CartPose::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ForceMasterPub.CartPose)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double x = 1;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->x(), output);
  }

  // double y = 2;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->y(), output);
  }

  // double z = 3;
  if (this->z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->z(), output);
  }

  // double a = 4;
  if (this->a() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->a(), output);
  }

  // double b = 5;
  if (this->b() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->b(), output);
  }

  // double c = 6;
  if (this->c() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->c(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ForceMasterPub.CartPose)
}

::google::protobuf::uint8* CartPose::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ForceMasterPub.CartPose)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double x = 1;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->x(), target);
  }

  // double y = 2;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->y(), target);
  }

  // double z = 3;
  if (this->z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->z(), target);
  }

  // double a = 4;
  if (this->a() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->a(), target);
  }

  // double b = 5;
  if (this->b() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->b(), target);
  }

  // double c = 6;
  if (this->c() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(6, this->c(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ForceMasterPub.CartPose)
  return target;
}

size_t CartPose::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ForceMasterPub.CartPose)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // double x = 1;
  if (this->x() != 0) {
    total_size += 1 + 8;
  }

  // double y = 2;
  if (this->y() != 0) {
    total_size += 1 + 8;
  }

  // double z = 3;
  if (this->z() != 0) {
    total_size += 1 + 8;
  }

  // double a = 4;
  if (this->a() != 0) {
    total_size += 1 + 8;
  }

  // double b = 5;
  if (this->b() != 0) {
    total_size += 1 + 8;
  }

  // double c = 6;
  if (this->c() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CartPose::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ForceMasterPub.CartPose)
  GOOGLE_DCHECK_NE(&from, this);
  const CartPose* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CartPose>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ForceMasterPub.CartPose)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ForceMasterPub.CartPose)
    MergeFrom(*source);
  }
}

void CartPose::MergeFrom(const CartPose& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ForceMasterPub.CartPose)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.z() != 0) {
    set_z(from.z());
  }
  if (from.a() != 0) {
    set_a(from.a());
  }
  if (from.b() != 0) {
    set_b(from.b());
  }
  if (from.c() != 0) {
    set_c(from.c());
  }
}

void CartPose::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ForceMasterPub.CartPose)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CartPose::CopyFrom(const CartPose& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ForceMasterPub.CartPose)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CartPose::IsInitialized() const {
  return true;
}

void CartPose::Swap(CartPose* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CartPose::InternalSwap(CartPose* other) {
  using std::swap;
  swap(x_, other->x_);
  swap(y_, other->y_);
  swap(z_, other->z_);
  swap(a_, other->a_);
  swap(b_, other->b_);
  swap(c_, other->c_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CartPose::GetMetadata() const {
  protobuf_force_5fmaster_5fpub_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_force_5fmaster_5fpub_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace ForceMasterPub
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ForceMasterPub::PublishData* Arena::CreateMaybeMessage< ::ForceMasterPub::PublishData >(Arena* arena) {
  return Arena::CreateInternal< ::ForceMasterPub::PublishData >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ForceMasterPub::JointPosition* Arena::CreateMaybeMessage< ::ForceMasterPub::JointPosition >(Arena* arena) {
  return Arena::CreateInternal< ::ForceMasterPub::JointPosition >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ForceMasterPub::CartPose* Arena::CreateMaybeMessage< ::ForceMasterPub::CartPose >(Arena* arena) {
  return Arena::CreateInternal< ::ForceMasterPub::CartPose >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
