#ifndef UR_COMM_MESSAGE_TYPE_H
#define UR_COMM_MESSAGE_TYPE_H

namespace message_types
{
	enum MessageType :int8_t                  //不限定作用域枚举类型
	{
		ROBOT_STATE = 16,
		ROBOT_MESSAGE = 20,
		PROGRAM_STATE_MESSAGE = 25
	};

	enum RobotStateMessageType :int8_t
	{
		ROBOT_MODE_DATA = 0,
		JOINT_DATA = 1,
		TOOL_DATA = 2,
		MASTERBOARD_DATA = 3,
		CARTESIAN_INFO = 4,
		KINEMATICS_INFO = 5,
		CONFIGURATION_DATA = 6,
		FORCE_MODE_DATA = 7,
		ADDITIONAL_INFO = 8,
		CALIBRATION_DATA = 9,
		SAFETY_DATA = 10,             //add
		TOOL_COMMUNICATION_INFO = 11    //add
	};

	enum RobotMessageType :int8_t
	{
		ROBOT_MESSAGE_TEXT = 0,
		ROBOT_MESSAGE_PROGRAM_LABEL = 1,
		ROBOT_MESSAGE_TYPE_POPUP = 2, //(MESSAGE_TYPE_PROGRAM_STATE_MESSAGE = 25)    //? excel: ROBOT_MESSAGE_TYPE_POPUP
		ROBOT_MESSAGE_VERSION = 3,
		ROBOT_MESSAGE_SAFETY_MODE = 5,
		ROBOT_MESSAGE_ERROR_CODE = 6,
		ROBOT_MESSAGE_KEY = 7,
		ROBOT_MESSAGE_REQUEST_VALUE = 9,
		ROBOT_MESSAGE_RUNTIME_EXCEPTION = 10
	};

	enum ProgramStateMessageType :int8_t
	{
		PROGRAM_STATE_MESSAGE_GLOBAL_VARIABLES_SETUP = 0,
		PROGRAM_STATE_MESSAGE_GLOBAL_VARIABLES_UPDATE = 1,
		PROGRAM_STATE_MESSAGE_VARIABLE_UPDATE = 2,
	};

	enum RobotStateType18 :int8_t
	{
		ROBOT_RUNNING_MODE = 0,
		ROBOT_FREEDRIVE_MODE = 1,
		ROBOT_READY_MODE = 2,
		ROBOT_INITIALIZING_MODE = 3,
		ROBOT_SECURITY_STOPPED_MODE = 4,
		ROBOT_EMERGENCY_STOPPED_MODE = 5,
		ROBOT_FATAL_ERROR_MODE = 6,
		ROBOT_NO_POWER_MODE = 7,
		ROBOT_NOT_CONNECTED_MODE = 8,
		ROBOT_SHUTDOWN_MODE = 9,
		ROBOT_SAFEGUARD_STOP_MODE = 10
	};

	enum RobotStateType30 :int8_t
	{
		ROBOT_MODE_DISCONNECTED = 0,
		ROBOT_MODE_CONFIRM_SAFETY = 1,
		ROBOT_MODE_BOOTING = 2,
		ROBOT_MODE_POWER_OFF = 3,
		ROBOT_MODE_POWER_ON = 4,
		ROBOT_MODE_IDLE = 5,
		ROBOT_MODE_BACKDRIVE = 6,
		ROBOT_MODE_RUNNING = 7,
		ROBOT_MODE_UPDATING_FIRMWARE = 8
	};
}

#endif